blog/urls.py
from django.urls import path, include
from .views import blogs, blog_detail

app_name = "blog"

urlpatterns = [
    path('', blogs, name="blogs"),
    path('<int:blog_id>/', blog_detail, name="blog_detail")
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from portfolio.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page,name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    date_created = models.DateTimeField(
        auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "بلاگ"
        verbose_name_plural = "بلاگ ها"

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان')
    description = models.CharField(max_length=250, verbose_name='توضیح کوتاه')
    image = models.ImageField(
        upload_to='portfolio/images', verbose_name='عکس')
    url = models.URLField(blank=True, null=True, verbose_name="یو آر ال")

    def __str__(self):
        return self.title
    
    class Meta : 
        verbose_name = "پروژه"
        verbose_name_plural = "مدیریت پروژه ها"

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
# Create your views here.


def blogs(request):
    blog_models = Blog.objects.order_by('-date_created')  # [:2]
    context = {
        "content": "This is Blog Section",
        "blog_models": blog_models
    }
    return render(request, "blog_page.html", context)


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)

    context = {
        "content":"This is Blog Detail :",
        "blog": blog
    }
    return render(request, "blog_detail.html", context)

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.


def home_page(request):
    project_models = Project.objects.all()
    context = {
        "content": "This is My Home Page",
        "project_models": project_models
    }
    return render(request, "home_page.html", context)

blog/templates/blog_detail.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>{{ content }}</h1>


<h2 dir="rtl">{{ blog.title }}</h2>
<p dir="rtl">{{ blog.description }}</p>
<h5 dir="rtl">{{ blog.date_created }}</h5>
<a  href="{% url 'blog:blogs' %}">برگشت به بلاگ</a>
{% endblock %}

blog/templates/blog_page.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>{{ content }}</h1>
<h2>فریبرز {{ blog_models.count }} تا بلاگ نوشته است </h2>
<h2>fariborz has written {{ blog_models.count }} blog{{ blog_models.count|pluralize }}</h2>
{% for blog in blog_models %}
<a href="{% url 'blog:blog_detail' blog.id  %}">
    <h1 dir="rtl">{{ blog.title }}</h1>
</a>
<h5 dir="rtl">{{ blog.date_created }}</h5>
<p dir="rtl">{{ blog.description|truncatechars:60 }}</p>
{% endfor %}
{% endblock %}

portfolio/templates/home_page.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<h1>{{ content }}</h1>
<a href="{% url 'blog:blogs'  %}">Blog</a><br>
<a href="{% static 'images/golestan.pdf' %}"><img src="{% static 'images/xx.jpg' %}" style="width: 350; height: 350;">
</a>
{% for project in project_models %}
<h2>{{ project.title }}</h2>
<h2>{{ project.description }}</h2>
<a href="{{ project.url }}">
    <img src="{{ project.image.url }}" style="width: 250; height: 250;">
</a>
{% endfor %}
{% endblock %}

portfolio/templates/shared/base.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:blogs' %}">Blog</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>
    {% block content %}{% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
</body>

</html>